[package]
name = "my_tracy_musl"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { version = "0.1.41" }
tracing-log = "0.2"
tracing-subscriber = { version = "~0.3.19", features = ["chrono", "fmt", "tracing-log"] }
tracing-tracy = { version = "0.11.4", default-features = true }